### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [gadgetchaser/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the site looks good. You used some good technique here and your html was very efficient. Take a look at the issues I created as they will help you optimize some things and reorganize your html a little. Here is a good article with some examples: 
http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by gadgetchaser** [comment]
Thank you for your feedback. Beginners overthinking! Looking forward to the next exercise.
